[package]
name = "ser"
version = "0.1.0"
authors = ["Jonah Simpson <jonahs99@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4"
clap = { version = "4.4", features = ["derive"] }

